// src/components/Vue/Audio/AudioContext.vue
<script>
import { provide, onUnmounted } from 'vue'

export const key = Symbol();

export default {
  setup () {
    const audioContext = new AudioContext()

    onUnmounted(() => audioContext.close())

    provide(key, {
      audioContext,
      parentNode: audioContext.destination
    })
  }
}
</script>

<template>
  <slot/>
</template>

// src/components/Svelte/Audio/AudioContext.svelte
<script context="module">
	export const key = {};
</script>

<script>
	import { setContext, onDestroy } from 'svelte';

  	const audioContext = new AudioContext();

	setContext(key, {
		audioContext,
		parentNode: audioContext.destination
	});
	
	onDestroy(() => audioContext.close());
</script>

<slot />
