// src/components/React/Audio/GainNode.tsx
import React, { useEffect, useContext, useMemo } from 'react';
import { AudioContextContext } from './AudioContext';

const GainNode: React.FC<{ volume?: number }> = ({ children, volume }) => {
  const { audioContext, parentNode } = useContext(AudioContextContext);

  const gainNode = useMemo(() => {
    const node = audioContext.createGain();
    node.connect(parentNode);
    node.gain.value = volume || 0.2;

    return node;
  }, []);

  const providerData = useMemo(
    () => ({
      audioContext,
      parentNode: gainNode
    }),
    [volume]
  );

  useEffect(() => {
    const endTime = audioContext.currentTime + .1;
    gainNode.gain.linearRampToValueAtTime(volume, endTime);
  }, [volume]);

  return (
    <AudioContextContext.Provider value={providerData}>
      {children}
    </AudioContextContext.Provider>
  );
};

export default GainNode;

// src/components/Svelte/Audio/GainNode.svelte
<script>
	import { getContext, setContext, beforeUpdate } from 'svelte';
	
	export let volume = .2;
	
	const parentNode = getContext('audio-node');
	const audioContext = getContext('audio-context');
	
	const gainNode = audioContext.createGain();
	gainNode.connect(parentNode);
	gainNode.gain.value = volume;
	
	beforeUpdate(() => {
		const endTime = audioContext.currentTime + .2;
		gainNode.gain.linearRampToValueAtTime(volume, endTime);
	});
	
	setContext('audio-node', gainNode);
</script>

<slot />
