// src/components/Vue/Audio/GainNode.vue
<script>
import { inject, provide, onUpdated } from 'vue'
import { key } from './AudioContext.vue'

export default {
  props: {
    volume: Number
  },
  setup(props) {
    const { audioContext, parentNode } = inject(key)

    const gainNode = audioContext.createGain()
    gainNode.connect(parentNode)
    gainNode.gain.value = props.volume ?? 0.2

    onUpdated(() => {
      const endTime = audioContext.currentTime + .1
      gainNode.gain.linearRampToValueAtTime(props.volume, endTime)
    })

    provide(key, {
      audioContext,
      parentNode: gainNode
    })
  }
}
</script>

<template>
  <slot/>
</template>

// src/components/Svelte/Audio/GainNode.svelte
<script>
	import { getContext, setContext, beforeUpdate } from 'svelte';
	import { key } from './AudioContext.svelte';

	export let volume = .2;
	
	const { audioContext, parentNode } = getContext(key);
	
	const gainNode = audioContext.createGain();
	gainNode.connect(parentNode);
	gainNode.gain.value = volume;
	
	beforeUpdate(() => {
		const endTime = audioContext.currentTime + .2;
		gainNode.gain.linearRampToValueAtTime(volume, endTime);
	});
	
	setContext(key, {
		audioContext,
		parentNode: gainNode,
	});
</script>

<slot />
