// src/components/Vue/Audio/index.vue
<template>
  <button @click="playPause">
    {{ isPlaying ? 'Stop Audio' : 'Play Audio' }}
  </button>

  <input type="range" min="100" max="1000" step="5" @input="changeFrequency">

  <AudioContextNode v-if="isPlaying">
    <GainNode :volume=".2">
      <OscillatorNode :frequency="frequency" type="sine" />
    </GainNode>
  </AudioContextNode>
</template>

<script> 
  import { ref } from 'vue'

  import AudioContextNode from './AudioContext.vue'
  import GainNode from './GainNode.vue'
  import OscillatorNode from './OscillatorNode.vue'

  export default {
    components: {
      AudioContextNode,
      GainNode,
      OscillatorNode
    },
    setup() {
      const isPlaying = ref(false)
      const playPause = () => 
        isPlaying.value = !isPlaying.value

      const frequency = ref(300);
      const changeFrequency = (e) => 
        frequency.value = Number(e.currentTarget.value);

      return { isPlaying, playPause, frequency, changeFrequency }
    }
  }
</script>

<style>
</style>

// src/components/Svelte/Audio/index.svelte
<script>
	import GainNode from './GainNode.svelte';
	import Oscillator from './Oscillator.svelte';
	import AudioContext from './AudioContext.svelte';
	
	let showAudio = false; 

	let frequency = 300;
	const changeFrequency = (e) => 
		frequency = Number(e.currentTarget.value);
</script>

<button on:click={() => showAudio = !showAudio}>
	{showAudio ? 'Stop' : 'Play'} Audio
</button>

<input 
	type="range" min="100" max="1000" step="5"
	value={frequency}
	on:input={changeFrequency}
/>

{#if showAudio}
	<AudioContext>
		<GainNode volume={.2}>
			<Oscillator bind:frequency type="sine" />
		</GainNode>
	</AudioContext>
{/if}
