// src/components/React/Audio/AudioContext.tsx
import React, { useEffect, useMemo } from 'react';

export const AudioContextContext = React.createContext({
  audioContext: null,
  parentNode: null
});

const AudioContextNode: React.FC = ({ children }) => {
  const audioContext = useMemo(() => new window.AudioContext(), []);

  const providerData = useMemo(
    () => ({
      audioContext,
      parentNode: audioContext.destination
    }),
    []
  );

  useEffect(() => {
    return () => audioContext.close();
  }, []);

  return (
    <AudioContextContext.Provider value={providerData}>
      {children}
    </AudioContextContext.Provider>
  );
};

export default AudioContextNode;

// src/components/Solid/Audio/AudioContext.tsx
import { createContext, useContext, onCleanup } from 'solid-js'

const AudioContextContext = createContext({
  audioContext: null,
  parentNode: null
});

export const AudioContextNode = (props) => {
  const audioContext = new AudioContext();

  const providerData = {
    audioContext,
    parentNode: audioContext.destination
  };

  onCleanup(() => audioContext.close());

  return (
    <AudioContextContext.Provider value={providerData}>
      {props.children}
    </AudioContextContext.Provider>
  );
};

export const GainNode = (props) => {
  const { audioContext, parentNode } = useContext(AudioContextContext);

  const gainNode = audioContext.createGain();
  gainNode.connect(parentNode);
  gainNode.gain.value = props.volume || 0.2;

  const providerData = {
    audioContext,
    parentNode: gainNode
  };

  return (
    <AudioContextContext.Provider value={providerData}>
      {props.children}
    </AudioContextContext.Provider>
  );
};

export const OscillatorNode = (props) => {
  const { audioContext, parentNode } = useContext(AudioContextContext);

  const oscillator = audioContext.createOscillator();
  oscillator.type = props.type || 'sine';
  oscillator.frequency.value = props.frequency || 100;
  oscillator.connect(parentNode);
  oscillator.start(0);

  return null;
};
