// src/components/React/Audio/index.tsx
/** @jsxImportSource react */
import { default as AudioContextNode } from './AudioContext';
import { default as GainNode } from './GainNode';
import { default as OscillatorNode } from './OscillatorNode';
import React, { useState } from 'react';

export default function App() {
  const [showAudio, setShowAudio] = useState(false);

  const [frequency, setFrequency] = useState(300);
  const changeFrequency = (e: React.SyntheticEvent<{ value: string }>) =>
    setFrequency(Number(e.currentTarget.value));

  return (
    <>
      <button onClick={() => setShowAudio(prev => !prev)}>
        {showAudio ? 'Stop' : 'Play'} Audio
      </button>

      <input 
        type="range" min="100" max="1000" step="5" 
        value={frequency}
        onInput={changeFrequency}
      />

      {showAudio && (
        <AudioContextNode>
          <GainNode volume={.2}>
            <OscillatorNode frequency={frequency} type='sine' />
          </GainNode>
        </AudioContextNode>
      )}
    </>
  );
}

// src/components/Solid/Audio/index.tsx
/** @jsxImportSource solid-js */
import { createSignal, Show } from "solid-js";
import { AudioContextNode, GainNode, OscillatorNode } from './AudioContext'

export default function App() {
  const [showAudio, setShowAudio] = createSignal(false);
  const [frequency, setFrequency] = createSignal(300);
  const changeFrequency = (e) =>
    setFrequency(Number(e.currentTarget.value));

  return (
    <section>
      <button onClick={() => setShowAudio(prev => !prev)}>
        {showAudio() ? 'Stop' : 'Play'} Audio
      </button>

      <input 
        type="range" min="100" max="1000" step="5" 
        value={frequency()}
        onInput={changeFrequency}
      />
  
      <Show when={showAudio()}>
        <AudioContextNode>
          <GainNode volume={.2}>
            <OscillatorNode frequency={frequency()} type='sine' />
          </GainNode>
        </AudioContextNode>
      </Show>
    </section>
  );
}
