// src/components/Vue/Tabs/TabContainer.vue
<template>
  <section class="tabs-container">
    <div class="tabs">
      <span 
        v-for="tab in tabs" 
        :key="tab" 
        :class="{ selected: tab === activeTab }"
        @click="activeTab = tab"
      >
        {{ tab }}
      </span>
    </div>
    <div class="content">
      <slot />
    </div>
  </section>
</template>

<script>
import { provide, ref } from 'vue'

export const key = Symbol()

export default {
  setup() {
    const tabs = ref([])
    const activeTab = ref('')

    provide(key, {
      addTab(label) {
        if (!tabs.value.length) activeTab.value = label
        tabs.value.push(label)
      },
      removeTab(label) {
        tabs.value = tabs.value.filter(tab => tab !== label)
      },
      activeTab
    })

    return { tabs, activeTab }
  }
}
</script>

// src/components/Svelte/Tabs/TabContainer.svelte
<script context="module">
	export const key = {};
</script>

<script>
	import { setContext } from 'svelte';
	import { writable } from 'svelte/store';
	
	let tabs = [];
	const activeTab = writable('');

	setContext(key, {
		addTab(label) {
			if (!tabs.length) activeTab.set(label);
			tabs = [...tabs, label];
		},
		removeTab(label) {
			tabs = tabs.filter(name => name !== label);
		},
		activeTab,
	});
</script>

<div class="tabs-container">
	<div class="tabs">
		{#each tabs as label}
			<span
				key={label}
				class:selected={label === $activeTab}
				on:click={() => $activeTab = label}
			>
				{label}
			</span>
		{/each}
	</div>
	<div class="content">
		<slot />
	</div>
</div>
