// src/components/Vue/Audio/OscillatorNode.vue
<script>
import { inject, provide, onUpdated } from 'vue'

export default {
  props: {
    frequency: Number,
    type: String
  },
  setup (props) {
    const { audioContext, parentNode } = inject('AUDIO_CONTEXT')

    const oscillator = audioContext.createOscillator()
    oscillator.type = props.type ?? 'sine'
    oscillator.frequency.value = props.frequency ?? 100
    oscillator.connect(parentNode)
    oscillator.start(0)

    onUpdated(() => {
      oscillator.type = props.type ?? 'sine'

      const endTime = audioContext.currentTime + .2;
      oscillator.frequency.linearRampToValueAtTime(props.frequency, endTime);
    })

    provide('AUDIO_CONTEXT', {
      audioContext,
      parentNode: oscillator
    })
  }
}
</script>

<template>
  <slot/>
</template>

// src/components/React/Audio/OscillatorNode.tsx
import React, { useEffect, useContext, useMemo } from 'react';
import { AudioContextContext } from './AudioContext';

interface Props {
    frequency?: number;
    type?: string;
}

const OscillatorNode: React.FC<Props> = ({ children, frequency, type }) => {
  const { audioContext, parentNode } = useContext(AudioContextContext);

  const oscillator = useMemo(() => {
    const node = audioContext.createOscillator();
    node.type = type || 'sine';
    node.frequency.value = frequency || 100;
    node.connect(parentNode);
    node.start(0);

    return node;
  }, []);

  const providerData = useMemo(
    () => ({
      audioContext,
      parentNode: oscillator
    }),
    [frequency, type]
  );

  useEffect(() => {
    oscillator.type = type ?? 'sine';
  }, [type]);
  
  useEffect(() => {
    const endTime = audioContext.currentTime + .2;
    oscillator.frequency.linearRampToValueAtTime(frequency, endTime);
  }, [frequency]);

  return (
    <AudioContextContext.Provider value={providerData}>
      {children}
    </AudioContextContext.Provider>
  );
};

export default OscillatorNode;
